# Generated by Django 5.2.14 on 2026-05-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(max_length=100),
        ),
    ]
